// Desafio10/src/App.vue
<script setup>

import Cronometro from './components/Cronometro.vue';
import Doacao from './components/Doacao.vue';
import Footer from './components/Footer.vue';
import Inicio from './components/Inicio.vue';

</script>

<template>

 <Inicio />
 <Cronometro />
 <Doacao />
 <Footer />
 
</template>

<style scoped lang="scss">

</style>

// Desafio06/src/App.jsx
import Footer from './components/Footer/Footer';
import Habilidades from './components/Habilidades/Habilidades';
import Header from './components/Header/Header';
import Inicio from './components/Inicio/Inicio';
import Projetos from './components/Projetos/Projetos';
import Servicos from './components/Servicos/Servicos';
import SobreMim from './components/SobreMim/SobreMim';

export default function App() {
  return (
    <>
      <Header />
      <Inicio />
      <SobreMim />
      <Projetos />
      <Servicos />
      <Habilidades />
      <Footer />
    </>
  );
}
